name: approval-demo
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build app
        run: echo "APP Building"
  Deploy-Dev:
    runs-on: ubuntu-latest
    needs: [Build]
    if: github.event_name == 'pull_request'
    environment:
      name: Development
      url: https://google.com
    steps:
      - name: Deploy to development
        run: |
          echo "APP deploying to develpment"
          echo $VARIABLE
  Deploy-Staging:
    runs-on: ubuntu-latest
    needs: ["Build"]
    if: github.event.ref == 'refs/heads/main'
    environment:
      name: Staging
      url: https://google.com
    steps:
      - name: Deploy app to staging
        run: echo "APP deploying to staging"
  Deploy-Production:
    runs-on: ubuntu-latest
    needs: ["Deploy-Staging"]
    environment:
      name: Production
      url: https://google.com
    steps:
      - name: Deploy app to Production
        run: echo "APP deploying to Production"